-- NeuralCanvas schema
-- Applied against the Supabase project sbnnaouddxqrqaofsjfc
--
-- A collaborative infinite canvas where ideas ("nodes") are embedded
-- client-side (in-browser AI, no external API calls) and auto-linked
-- by semantic similarity. Embeddings are stored as plain float arrays
-- (no pgvector extension assumed available on the free tier) and
-- similarity is computed client-side.

create extension if not exists "uuid-ossp";

-- Profiles: mirrors auth.users, one row per user
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  color text default '#6366f1',
  created_at timestamptz not null default now()
);

-- Canvases: a shared board. Owner + collaborators via canvas_members.
create table if not exists public.canvases (
  id uuid primary key default uuid_generate_v4(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Sans titre',
  is_public boolean not null default false,
  share_token text unique default encode(gen_random_bytes(9), 'base64'),
  created_at timestamptz not null default now()
);

create table if not exists public.canvas_members (
  canvas_id uuid not null references public.canvases(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'editor' check (role in ('owner', 'editor', 'viewer')),
  joined_at timestamptz not null default now(),
  primary key (canvas_id, user_id)
);

-- Nodes: an idea/sticky note on the canvas. Embedding computed client-side.
create table if not exists public.nodes (
  id uuid primary key default uuid_generate_v4(),
  canvas_id uuid not null references public.canvases(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  x double precision not null default 0,
  y double precision not null default 0,
  color text default '#fef08a',
  embedding jsonb,
  cluster_id int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Edges: links between nodes. kind='auto' = generated by the similarity
-- engine, kind='manual' = drawn by a user, kind='contradiction' = flagged.
create table if not exists public.edges (
  id uuid primary key default uuid_generate_v4(),
  canvas_id uuid not null references public.canvases(id) on delete cascade,
  source_id uuid not null references public.nodes(id) on delete cascade,
  target_id uuid not null references public.nodes(id) on delete cascade,
  kind text not null default 'auto' check (kind in ('auto', 'manual', 'contradiction')),
  weight double precision default 0,
  created_at timestamptz not null default now(),
  unique (source_id, target_id, kind)
);

-- Presence: ephemeral cursor positions, upserted frequently, no history kept.
create table if not exists public.presence (
  canvas_id uuid not null references public.canvases(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  x double precision not null default 0,
  y double precision not null default 0,
  updated_at timestamptz not null default now(),
  primary key (canvas_id, user_id)
);

create index if not exists nodes_canvas_id_idx on public.nodes(canvas_id);
create index if not exists edges_canvas_id_idx on public.edges(canvas_id);
create index if not exists canvas_members_user_id_idx on public.canvas_members(user_id);

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.canvases enable row level security;
alter table public.canvas_members enable row level security;
alter table public.nodes enable row level security;
alter table public.edges enable row level security;
alter table public.presence enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
drop policy if exists "profiles_upsert_own" on public.profiles;
create policy "profiles_upsert_own" on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id);

-- Canvas visibility: owner, member, or public (read-only for public unless member)
drop policy if exists "canvases_select" on public.canvases;
create policy "canvases_select" on public.canvases for select using (
  is_public = true
  or owner_id = auth.uid()
  or exists (select 1 from public.canvas_members m where m.canvas_id = id and m.user_id = auth.uid())
);
drop policy if exists "canvases_insert_own" on public.canvases;
create policy "canvases_insert_own" on public.canvases for insert with check (owner_id = auth.uid());
drop policy if exists "canvases_update_owner" on public.canvases;
create policy "canvases_update_owner" on public.canvases for update using (owner_id = auth.uid());
drop policy if exists "canvases_delete_owner" on public.canvases;
create policy "canvases_delete_owner" on public.canvases for delete using (owner_id = auth.uid());

drop policy if exists "canvas_members_select" on public.canvas_members;
create policy "canvas_members_select" on public.canvas_members for select using (
  user_id = auth.uid()
  or exists (select 1 from public.canvases c where c.id = canvas_id and c.owner_id = auth.uid())
);
drop policy if exists "canvas_members_insert_self_or_owner" on public.canvas_members;
create policy "canvas_members_insert_self_or_owner" on public.canvas_members for insert with check (
  user_id = auth.uid()
  or exists (select 1 from public.canvases c where c.id = canvas_id and c.owner_id = auth.uid())
);
drop policy if exists "canvas_members_delete_owner" on public.canvas_members;
create policy "canvas_members_delete_owner" on public.canvas_members for delete using (
  exists (select 1 from public.canvases c where c.id = canvas_id and c.owner_id = auth.uid())
);

-- Access to nodes/edges/presence follows canvas access
drop policy if exists "nodes_select" on public.nodes;
create policy "nodes_select" on public.nodes for select using (
  exists (
    select 1 from public.canvases c
    where c.id = canvas_id
      and (c.is_public = true or c.owner_id = auth.uid()
           or exists (select 1 from public.canvas_members m where m.canvas_id = c.id and m.user_id = auth.uid()))
  )
);
drop policy if exists "nodes_write" on public.nodes;
create policy "nodes_write" on public.nodes for all using (
  exists (
    select 1 from public.canvases c
    where c.id = canvas_id
      and (c.owner_id = auth.uid()
           or exists (select 1 from public.canvas_members m where m.canvas_id = c.id and m.user_id = auth.uid() and m.role in ('owner','editor')))
  )
) with check (author_id = auth.uid());

drop policy if exists "edges_select" on public.edges;
create policy "edges_select" on public.edges for select using (
  exists (
    select 1 from public.canvases c
    where c.id = canvas_id
      and (c.is_public = true or c.owner_id = auth.uid()
           or exists (select 1 from public.canvas_members m where m.canvas_id = c.id and m.user_id = auth.uid()))
  )
);
drop policy if exists "edges_write" on public.edges;
create policy "edges_write" on public.edges for all using (
  exists (
    select 1 from public.canvases c
    where c.id = canvas_id
      and (c.owner_id = auth.uid()
           or exists (select 1 from public.canvas_members m where m.canvas_id = c.id and m.user_id = auth.uid() and m.role in ('owner','editor')))
  )
);

drop policy if exists "presence_select" on public.presence;
create policy "presence_select" on public.presence for select using (
  exists (
    select 1 from public.canvases c
    where c.id = canvas_id
      and (c.is_public = true or c.owner_id = auth.uid()
           or exists (select 1 from public.canvas_members m where m.canvas_id = c.id and m.user_id = auth.uid()))
  )
);
drop policy if exists "presence_write_own" on public.presence;
create policy "presence_write_own" on public.presence for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Auto-create profile row on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)));
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Keep updated_at fresh on nodes
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists nodes_set_updated_at on public.nodes;
create trigger nodes_set_updated_at
  before update on public.nodes
  for each row execute procedure public.set_updated_at();
